In [1]:
import pandas as pd
import numpy as np

In [3]:
#Read the dataset in csv
tweets = pd.read_csv('Tweets.csv')
tweets.head(10)

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)
5,570300767074181121,negative,1.0000,Can't Tell,0.6842,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica seriously would pay $30 a fligh...,NaN,2015-02-24 11:14:33 -0800,NaN,Pacific Time (US & Canada)
6,570300616901320704,positive,0.6745,NaN,0.0000,Virgin America,NaN,cjmcginnis,NaN,0,"@VirginAmerica yes, nearly every time I fly VX...",NaN,2015-02-24 11:13:57 -0800,San Francisco CA,Pacific Time (US & Canada)
7,570300248553349120,neutral,0.6340,NaN,NaN,Virgin America,NaN,pilot,NaN,0,@VirginAmerica Really missed a prime opportuni...,NaN,2015-02-24 11:12:29 -0800,Los Angeles,Pacific Time (US & Canada)
8,570299953286942721,positive,0.6559,NaN,NaN,Virgin America,NaN,dhepburn,NaN,0,"@virginamerica Well, I didn'tâ€¦but NOW I DO! :-D",NaN,2015-02-24 11:11:19 -0800,San Diego,Pacific Time (US & Canada)
9,570295459631263746,positive,1.0000,NaN,NaN,Virgin America,NaN,YupitsTate,NaN,0,"@VirginAmerica it was amazing, and arrived an ...",NaN,2015-02-24 10:53:27 -0800,Los Angeles,Eastern Time (US & Canada)

In [10]:
is_positive = tweets['airline_sentiment'].str.contains("positive")
is_negative = tweets['airline_sentiment'].str.contains("negative")
is_neutral = tweets['airline_sentiment'].str.contains("neutral")

In [11]:
# In[4]:

positive_tweets = tweets[is_positive]
positive_tweets.shape


# In[5]:

negative_tweets = tweets[is_negative]
negative_tweets.shape


# In[6]:

neutral_tweets = tweets[is_neutral]
neutral_tweets.shape


# In[34]:

worst_airline = negative_tweets[['airline','airline_sentiment_confidence','negativereason']]
worst_airline

,airline,airline_sentiment_confidence,negativereason
3,Virgin America,1.0000,Bad Flight
4,Virgin America,1.0000,Can't Tell
5,Virgin America,1.0000,Can't Tell
15,Virgin America,0.6842,Late Flight
17,Virgin America,1.0000,Bad Flight
20,Virgin America,0.6705,Can't Tell
24,Virgin America,1.0000,Customer Service Issue
25,Virgin America,1.0000,Customer Service Issue
26,Virgin America,1.0000,Can't Tell
28,Virgin America,1.0000,Bad Flight
30,Virgin America,1.0000,Flight Booking Problems
32,Virgin America,1.0000,Customer Service Issue
33,Virgin America,1.0000,Customer Service Issue
39,Virgin America,1.0000,Customer Service Issue
41,Virgin America,0.6688,Flight Booking Problems
55,Virgin America,0.6939,Flight Booking Problems
61,Virgin America,1.0000,Customer Service Issue
66,Virgin America,1.0000,Customer Service Issue
67,Virgin America,1.0000,Late Flight
69,Virgin America,1.0000,Lost Luggage
73,Virgin America,1.0000,Flight Attendant Complaints
78,Virgin America,1.0000,Customer Service Issue
80,Virgin America,1.0000,Customer Service Issue
82,Virgin America,0.6792,Late Flight
83,Virgin America,1.0000,Can't Tell
84,Virgin America,1.0000,Can't Tell
85,Virgin America,1.0000,Flight Booking Problems
89,Virgin America,1.0000,Can't Tell
92,Virgin America,1.0000,Cancelled Flight
93,Virgin America,1.0000,Late Flight
...,...,...,...
14595,American,0.6541,Customer Service Issue
14596,American,1.0000,Customer Service Issue
14597,American,1.0000,Late Flight
14599,American,1.0000,Cancelled Flight
14601,American,1.0000,Late Flight
14603,American,0.6788,Cancelled Flight
14604,American,0.6440,Cancelled Flight
14605,American,1.0000,Flight Booking Problems
14606,American,1.0000,Cancelled Flight
14608,American,1.0000,Cancelled Flight
14609,American,1.0000,Flight Attendant Complaints
14610,American,1.0000,longlines
14612,American,1.0000,Cancelled Flight
14613,American,1.0000,Customer Service Issue
14614,American,1.0000,Customer Service Issue
14615,American,1.0000,Cancelled Flight
14616,American,1.0000,Cancelled Flight
14618,American,1.0000,Bad Flight
14620,American,1.0000,Customer Service Issue
14621,American,1.0000,Customer Service Issue
14622,American,1.0000,Late Flight
14624,American,1.0000,Can't Tell
14626,American,1.0000,Late Flight
14627,American,1.0000,Cancelled Flight
14629,American,1.0000,Customer Service Issue
14631,American,1.0000,Bad Flight
14633,American,1.0000,Cancelled Flight
14634,American,0.6684,Late Flight
14636,American,1.0000,Customer Service Issue
14638,American,1.0000,Customer Service Issue

In [17]:
cnt_worst_airline = worst_airline.groupby('airline', as_index=False).count()
cnt_worst_airline.sort_values('negativereason', ascending=False)

          airline  airline_sentiment_confidence  negativereason
0        American                          1960            1960
1           Delta                           955             955
2       Southwest                          1186            1186
3      US Airways                          2263            2263
4          United                          2633            2633
5  Virgin America                           181             181

In [19]:
best_airline = positive_tweets[['airline','airline_sentiment_confidence']]
cnt_best_airline = best_airline.groupby('airline', as_index=False).count()
cnt_best_airline.sort_values('airline_sentiment_confidence', ascending=False)

          airline  airline_sentiment_confidence
2       Southwest                           570
1           Delta                           544
4          United                           492
0        American                           336
3      US Airways                           269
5  Virgin America                           152

In [20]:
motivation = negative_tweets[['airline','negativereason']]
cnt_bad_flight_motivation = motivation.groupby('negativereason', as_index=False).count()
cnt_bad_flight_motivation.sort_values('negativereason', ascending=False)

                negativereason  airline
9                    longlines      178
8                 Lost Luggage      724
7                  Late Flight     1665
6      Flight Booking Problems      529
5  Flight Attendant Complaints      481
4              Damaged Luggage       74
3       Customer Service Issue     2910
2             Cancelled Flight      847
1                   Can't Tell     1190
0                   Bad Flight      580